config/routes.rb
Rails.application.routes.draw do
  get 'about',           to: 'pages#about',      as: :about
  get 'contact',         to: 'pages#contact',    as: :contact

  devise_for :users
  root to: 'pages#home'

  resources :users
  resources :pets do
    resources :bookings, only: [:delete,:new, :edit, :update, :create, :show, :index]
  end
  resources :bookings do
    resources :reviews, only: [:new, :create, :show, :index]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :pet
  belongs_to :user
  #  in future: has_many :reviews, dependent: :destroy

  validates :start_date, uniqueness: true, presence: true
  validates :end_date, uniqueness: true, presence: true

  validate :end_after_start
  validate :date_cannot_predate

  private

  def end_after_start
    return "must be after the start date" unless end_date < start_date
  end

  def date_cannot_predate
    return "cannot pre-date today" unless start_date < Date.today
  end
end

app/models/pet.rb
class Pet < ApplicationRecord
  belongs_to :user


  has_one_attached :photo


  has_many :bookings, dependent: :destroy

  validates :name, :description, presence: true

  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?

  # include PgSearch::Model
  # pg_search_scope :search_by_name_and_location,
  # against: [ :name],
  # using: {
  #   tsearch: { prefix: true }
  # }

  def unavailable_dates
    bookings.pluck(:start_date, :end_date).map do |range|
      { from: range[0], to: range[1] }
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  # has_secure_password
  has_many :pets, dependent: :destroy
  has_many :bookings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  include Pundit

  # Pundit: white-list approach.
  # after_action :verify_authorized, except: :index, unless: :skip_pundit?
  # after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  # SEVEN CRUD ACTIONS
  before_action :find_booking, only: [:show, :edit, :update, :destroy]
  before_action :set_pet, except: [:index]
  # before action = params not needed == DNR !

  def index
    @booking = Booking.all
  end

  def show
  end

  def new
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.pet = @pet
    @booking.user = current_user
    if @booking.save!
      redirect_to bookings_path
    else
      render :new
    end
  end

  def update
    @booking = Booking.new(booking_params)
    redirect_to booking_path(@booking)
  end

  def delete
    @booking.destroy
    redirect_to booking_path(@booking)
  end

  private

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def booking_params
    params.require(:booking).permit( :start_date, :end_date)
  end

  def find_booking
    @booking = Booking.find(params[:id])
  end

  def future_booking
    @future_bookings = bookings.where("start_date >= '#{Date.today}'")
  end

  def set_pet
    @pet = Pet.find(params[:pet_id])
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  skip_before_action :authenticate_user!, only: :about

  def home
    @pets = Pet.limit(3).order('created_at DESC');
    @bookings = Booking.limit(1).order('created_at DESC');
  end

  def about
  end
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    # if params[:query].present?
    #     @pets = Pet.search_by_name(params[:query])
    #   else
    @pets = policy_scope(Pet).order(created_at: :desc)
    #    @pets = Pet.all
  end

  def show
    @pet = Pet.find(params[:id])

    @booking = Booking.new
  end

  def new
    @pet = Pet.new
    authorize @pet
  end

  def create
    @pet = Pet.new(pet_params[:pet])
    @pet.user_id = current_user
    authorize @pet
    if @pet.save
      redirect_to pet_path(@pet)
    else
      render :new
    end
  end

  def edit
    @pet = Pet.find(params[:id])
    @pet.edit(params[:pet])
  end

  def update
    @pet.update(pet_params)
    redirect_to pet_path(@pet)
  end

  def destroy
    @pet = Pet.find(params[:id])
    authorize @pet
    @pet.destroy
    redirect_to pets_path
  end

  private

  def pet_params
    params.require(:pet).permit(:name, :description, :price, :availability)
  end

  def find_pet
    @pet = Pet.find(params[:id])
    authorize @pet
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    if @user.save
      redirect_to :sessions_new
    else
      render "new"
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :password, :password_confirmation)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User
    sign_out :user
    redirect_to root_path
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    if @user.save
      redirect_to :sessions_new
    else
      render "new"
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password)
  end

  def user_pets
    @pets = Pet.where(user_id: current_user)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_form.html.erb
<div class="p-5 mt-5 shadow rounded justify-content-center">
  <%= simple_form_for [@pet, @booking] do |f| %>
    <%= f.input :start_date, html5: true, input_html: {class: "datepicker"}  %>
    <%= f.input :end_date, html5: true, input_html: {class: "datepicker"}  %>
    <%= f.button :submit, "Book Pet", class: 'btn btn-primary'%>
  <% end %>
</div>

app/views/bookings/_new.html.erb
<div class="modal fade" id="new_booking_modal" role="dialog">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Book <%= @pet.name %></h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
        </button>
      </div>
      <div class="modal-body">
        <%= simple_form_for [@pet, @booking], data: { unavailable_dates: @pet.unavailable_dates.to_json } do |f| %>
          <%= f.input :start_date, as: :string, required: false, input_html: {class: "datepicker"} %>
      <%= f.input :end_date, as: :string, required: false, input_html: {class: "datepicker"} %>
      <%= f.button :submit, "Book This Pet", class: 'btn btn-primary', method: :create, data:{ confirm: "Confirm Booking"}%>
        <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/bookings/edit.html.erb
<div class="container">
  <div class="form-wrapper" style="width: 300px; margin: 0 auto;">
    <h3><%= @pet.name %></h3>

    <%= simple_form_for [@pet, @booking], data: { unavailable_dates: @pet.unavailable_dates.to_json }, html:{id: :edit_booking} do |f| %>
      <%= f.input :start_date, as: :string, required: false, input_html: {class: "datepicker"} %>
      <%= f.input :end_date, as: :string, required: false, input_html: {class: "datepicker"} %>
      <%= f.button :submit, "Book This Pet!", class: 'btn btn-primary'%>
    <% end %>
  </div>
</div>

app/views/bookings/index.html.erb
<h1 class="text-center p-2">Your Upcoming Bookings</h1>




<div class="container">
  <div class="row   justify-content-center ">
  <% current_user.bookings.each do |book|%>
    <div class="card-pet" >
      <div class= "card-pet-infoshow">
       <%= book.pet.name   %>
        <div class="card-product-infos">
          <div class="card-pet-details">
            <div class="card-pet-text">

              <%= book.start_date  %>
              <%= book.end_date  %>
            </div>
          </div>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/bookings/new.html.erb
<div class="container">
  <div class="row justify-content-center" style="margin: 24px;">
    <h1 style = "text-align: center;">New Booking  </h1>
    <div class="col-6">
      <%= simple_form_for [@pet, @booking] do |f|%>
        <%= f.input :start_date, as: :date, html5: true %>
        <%= f.input :end_date, as: :date, html5: true %>
        <div class="row justify-content-center">
          <%= f.submit class: 'btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/bookings/show.html.erb
<div class="container-hero">
  <div class="container-info shadow bg-white rounded m-3 p-3">
    <h1><%= @booking.pet.name %></h1>
        <p>Price £<%= @booking.cost %></p>
        <p>Dates <%= @booking.start_date.strftime("%d-%m-%Y") %> to <%= @booking.end_date.strftime("%d-%m-%Y") %></p>
        <p>Location <%= @booking.pet.location %> </p>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<head>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
</head>
<body>
  <div class="container">
    <%= render 'shared/navbar' %>
    <p.class="notice"><%= notice %></p>
    <p.class="alert"><%= notice %></p>
    <%= yield %>
  </div>
    <div class="footer">
      <div class="footer-links">
        <a href="#"><i class="fab fa-github"></i></a>
        <a href="#"><i class="fab fa-instagram"></i></a>
        <a href="#"><i class="fab fa-facebook"></i></a>
        <a href="#"><i class="fab fa-twitter"></i></a>
        <a href="#"><i class="fab fa-linkedin"></i></a>
      </div>
    </div>
</body>

app/views/pages/about.html.erb
<center><h1>Nice to meet you!</h1></center>

<div class="container" style="linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url()">
Join like minded people in your local area who are part of the newest pet-loving community. Make someones day, sign up, become members and share the happiness pets give.
<br><br>
Great to fit around work   <i class="fa-solid fa-briefcase"></i>
<br>Or on holiday   <i class="fa-solid fa-car"></i>
<br>Meet new friends  <i class="fas fa-dog"></i>
<br><br>
Purrrrito brings together animal lovers to borrow & share pets. We connect pet owners with trusted local pet lovers who would love to look after their pets.
</div>

app/views/pages/home.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PURRRRITO</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
</head>
<body>
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1605001011156-cbf0b0f67a51?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1374&q=80);">
  <div class="container">
    <h1>Purrrrito allows you to borrow an adorable pet!</h1>
      <p>Add the joy of pets to your life.</p>
    <a class="btn btn-flat" href="pets">Browse Pets!</a>
  </div>
</div>
<br>


<div class="container">
 <div class="cards">
  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1611611158876-41699b77a059?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1471&q=80)">
    Doggo
  </div>
<div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1555685812-4b943f1cb0eb?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1470&q=80)">
    Kit Kats
</div>
<div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1596138252452-463802fb8fc1?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1470&q=80)">
    Exotic
  </div>
</div>


</body>
</html>

app/views/pages/show.html.erb
<p>test</p>

app/views/pets/_form.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-12 col-md-6 offset-lg-3">
      <div class="p-5 mt-5 rounded justify-content-center">
        <%= simple_form_for @pet, html: { class: "form-new"} do |f| %>
          <%= f.input :name, :input_html => { :class => 'foo' }%>
          <%= f.input :description %>
          <%= f.input :location, input_html: { data: { geocoder_target: "address" } }, wrapper_html: { data: { controller: "geocoder", geocoder_api_key_value: ENV['MAPBOX_API_KEY'] } } %>
          <%= f.input :price, input_html: { min: 0, step: 'any' } %>
          <%= f.input :category, collection: ["Cat", "Dog", "Exotic"], as: :select %>
          <%= f.input :image_url %>
          <%= f.input :availability %>
          <%= f.submit %>
        <% end %>
       <%= link_to 'back', pets_path, class: "btn btn-primary" %>
     </div>
    </div>
  </div>
</div>

app/views/pets/index.html.erb
<div class="container ">
  <div class="row pt-8">
    <%= form_tag pets_path, method: :get do %>
      <%= text_field_tag :query, params[:query], class: "form-control", placeholder: "Find a pet" %>
      <%= submit_tag "search a pet", class: "btn btn-primary submit" %>
      <% end %>
  </div>
</div>

<div class="container">
<h1 style="center">Browse Pets</h1>
    <div class="cards">
      <% @pets.each do |pet| %>
        <div class="row ">
          <div><h3><%= link_to pet.name, pet_path(pet) %></h3>
            <div class="card-pet" >
              <% if pet.photo.attached? %>
                <%= cl_image_tag pet.photo.key, height: 100, width: 100, crop: :pad %>
              <% else %>
                <%= img_src="https://unsplash.com/photos/JmJDyFUSYWI" %>
              <% end %>
                <div class="card-product-infos">
                    <div class="card-pet-details">
                      <div class="card-pet-text">
                          <p>Hi! I'm <%= link_to pet.name, pet_path(pet) %></p>
                          <p>My personality is: <%= pet.description %></p>
                            <div class="card-pet-infos">
                              <p>Lets hang for £<%= pet.price %> a day!</p>
                            </div>
                        </div>
                    </div>
                  </div>
                </div>
              </div>
        </div>
        <% end %>
    </div>
</div>

app/views/pets/new.html.erb
<H1>Create a New Pet Profile</h1>

<%= render 'form', pet: @pet %>

<%= link_to 'Back', pet_path %>

<%= simple_form_for(@pet) do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.input :location, input_html: { data: { geocoder_target: "address" } }, wrapper_html: { data: { controller: "geocoder", geocoder_api_key_value: ENV['MAPBOX_API_KEY'] } } %> %>
  <%= f.input :price %>
  <%= f.input :availability %>
  <%= f.input :photo, as: :file %>
  <%= f.submit %>
  <%= f.button :submit, class: "btn btn-primary" %>
<% end %>


<%#

 <div class="banner-new">
   <div class="container">
     <div class="card">
      <%= render 'form' %>
    <%# </div>
   </div>
</div> %> %>

app/views/pets/show.html.erb
<div class="containair ">
  <div class="row   justify-content-center ">
    <div class="card-pet-show" >
                      <% if @pet.photo.attached? %>
                        <%= cl_image_tag @pet.photo.key, height: 180, width: 180, crop: :pad %>
                        <% else %>
                        <%= img_src="https://unsplash.com/photos/JmJDyFUSYWI" %>
                      <% end %>
                      <div class= "card-pet-infoshow"> </div>
                        <div class="card-product-infos">

                          <div class="card-pet-details">
                            <div class="card-pet-text">
                                <p>This lovely pet is  <%= @pet.name %></p>
                                <p>This Pet is  <%= @pet.description %> </p>
                                  <div class="card-pet-infos">
                                    <p>Spend some time with <%= @pet.name %>.</p>
                                  </div>
                                  <h3><%= link_to "Book #{@pet.name}",    new_pet_booking_path(@pet, @booking) %></h3>

                                  <p><%= link_to "Back home", pets_path %></p>
                            </div>
                          </div>
                        </div>
                      </div>
    </div>
  </div>
</div>

app/views/shared/_alerts.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "/", class: "navbar-brand" do %>
      <%= image_tag "https://res.cloudinary.com/bunkyboy/image/upload/v1653128964/Screenshot_2022-05-21_at_11.29.07_am_qcqncg.png" %>
    <% end %>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", "/", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Pets", pets_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Bookings", bookings_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item active">
            <%= link_to "Home", "/", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "About", about_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Log In", new_user_session_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Browse Pets", pets_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>